{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.0.0" %}
{% set sha256 = "a0d425a0fc7c7e3f2c92a272ffaffbd913005556b4443e1887d2e1718d902887" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pname }}-{{ version }}.tar.gz
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - libxml2 2.9.*
  run:
    - libxml2 2.9.*

test:
  commands:
    - hwloc-ls

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD 3-Clause
  license_file: COPYING
  summary: 'Portable Hardware Locality (hwloc)'

extra:
  recipe-maintainers:
    - inducer
