{% set name = "libhwloc" %}
{% set pname = "hwloc" %}
{% set version = "2.0.1" %}
{% set sha256 = "f1156df22fc2365a31a3dc5f752c53aad49e34a5e22d75ed231cd97eaa437f9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pname }}-{{ version }}.tar.gz
  url: https://www.open-mpi.org/software/hwloc/v{{ '.'.join(version.split('.')[:2]) }}/downloads/{{ pname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - libxml2 2.9.*
  run:
    - libxml2 2.9.*

test:
  commands:
    - hwloc-ls

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD 3-Clause
  license_file: COPYING
  summary: 'Portable Hardware Locality (hwloc)'

extra:
  recipe-maintainers:
    - inducer
