travis:
  secure:
    BINSTAR_TOKEN: fSS1rbMzkfysg75z5CVaOyF2+sR2hj3P7/rxjiVZl+Rc3JlkIEd/9fQo5MMINo7I9NvYHtgcoj22c1Ov+MKmkzHUyYN3MJPturBZj9vCy7nqWyNO9eGvIdkJUrq09IzajicM6WuJBtzyntBHbvHU+hT3JP3kFdyCN3FwFaWN0qXesBhVe6EJJBNniEuKtk1lKfNAYFGbIzEwLZXcVKfwrDDNZ1fm0UDDBr1p9acXqSJ4uL30i5SFxr4+Ju71v9gqyP+qS0/7Rngc0tkutWbx1xYSweKnnHk0fv4DfVL/ztIqRc2k3JyecDqg0g6knfExni4uE3cbzs930GWHnBGilG8oPsVMpddH8m6iUYpFn6+Su07WExPdjObJ+KlJiwhMBrLUDTqGIFTv5BRkD5KQc9Jt45LzpWjIJF6Y++jzgWYE0t9w193nbRVRLZ2+vNS0YxuIETUrOflERO14S91e2a6b8kirYey66Qoco3LpUX4hhHfG6mBPRdja/hjDpekSCFhpL8cKHdfpo2SRF/iLxJ5Fd0gBITNYGL/Rxn/LLITgH6t08gG2ttcUtOiNfIZhTbpCnIgoS0XrzSrDN1wOK36MVK3ONuqd35SJLwsDgQqKWXBvzgOt1nYlIsvmwsCAiqI8XUACb3kmWfeid0uqNjj/tgFnbzVleCUMhCTXinA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
