travis:
  secure:
    BINSTAR_TOKEN: KAi2+0dw1fBU8tzHtYJLo8oXL/5KmqcF6LBMG0v75K2cRF1vv5Mq+7PvOtYz6dubcNo1fMccVZV80sbUJeMlFDNoAdIelDEl0uOy27IfPAKz7g/BhNWRbgeeTvdS7hUhF/Xl/dGYQbdmzJA9ythNNkJzyutzQx+OGDD6VFuPU9FsGUW/SFxeJTHhPOOYHWzKDMiJ0upkJhLos35AdW6/2l0LwPJvVkaS4eKLvlNKOFcGIPqod36QeKanZQ2Jx7OG8uudGW7JZXQHZXgH1opnV1+ykL/fy0SGSoP/r71A+FxVipBUlKZ8+02AmFiXPuVp8UmgxlmfgDt8xpSm+xh8lolYxoFHgWGTw0xG+t7t4Yer0HPvMB80r/NbC88JsqEljguVd7wMEqMcmSzF5ShjpnaHR39Bz08qQi7Op5py5fMVfKnm48gsBFiqkxbzFf+dNktIpzDLRpEeuH1w4NPyehnyerGkW94Sx4wTm9Abj4VgyeU5rFmryAZHsYfd3oLzrNZRgLGlQCPdqiMtu8yg3lHldgu2j2q6wc//bqbdcuziLmJ85TpGnxDZnivQRBuPv0GAsbOY7yqTcEcSBVPS618fMs0y0osvwWnhMc0ZQrrXN50AA/yiY52m2sqr9WUZlnJ5/ApHsB0ONfBTrKuqS52KrjweWI0ucNRgqZoPoXg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
